# version: '3.8'
# services:
#   flask-app:
#     build: .
#     ports:
#       - "5000:5000"
#     environment:
#       - POSTGRES_USER=postgres
#       - POSTGRES_PASSWORD=postgres
#       - POSTGRES_DB=your_db
#       - SQLALCHEMY_DATABASE_URI=postgresql://postgres:postgres@db:5432/your_db
#     depends_on:
#       - db

#   db:
#     image: postgres:13
#     environment:
#       POSTGRES_USER: postgres
#       POSTGRES_PASSWORD: postgres
#       POSTGRES_DB: your_db
#     volumes:
#       - pgdata:/var/lib/postgresql/data

# volumes:
#   pgdata:


services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: petit_dev
      POSTGRES_PASSWORD: password
      POSTGRES_DB: petit_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - petit_network
  
  flask-app:
    build:
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: postgesql://petit_dev:password@db:5432/petit_db
    ports:
      - "5000:5000"
    depends_on:
      - db
    volumes:
      - ./app:/app
    networks:
      - petit_network
    command: bash -c "flask db upgrade && flask seed all && flask run"

volumes:
  postgres_data:

networks:
  petit_network:
